In [26]:
import numpy as np
import matplotlib.pyplot as plt
import json
from matplotlib import rcParams
rcParams['font.family'] = 'serif'
rcParams['font.size'] = 14

Module for computations

In [27]:
import FEM_utilities as FEM

Parameters:

In [28]:
a = 1000. # lenght [mm]
b = 200.  # width  [mm]
t = 1.5   # thickness [mm]

E = 72000. # modulus [MPa]
ν = 0.33   # Poisson's coefficient

F = 0.02   # load [N/mm]

Compute node coordinates, elements, constrained and loaded nodes

In [29]:
nx = 4
ny = 4

nodes, elements, constrained, loaded = FEM.Nodes(nx, ny, a, b)

In [30]:
nodes

array([[    1.,     0.,     0.,     0.],
       [    2.,   250.,     0.,     0.],
       [    3.,   500.,     0.,     0.],
       [    4.,   750.,     0.,     0.],
       [    5.,  1000.,     0.,     0.],
       [    6.,     0.,    50.,     0.],
       [    7.,   250.,    50.,     0.],
       [    8.,   500.,    50.,     0.],
       [    9.,   750.,    50.,     0.],
       [   10.,  1000.,    50.,     0.],
       [   11.,     0.,   100.,     0.],
       [   12.,   250.,   100.,     0.],
       [   13.,   500.,   100.,     0.],
       [   14.,   750.,   100.,     0.],
       [   15.,  1000.,   100.,     0.],
       [   16.,     0.,   150.,     0.],
       [   17.,   250.,   150.,     0.],
       [   18.,   500.,   150.,     0.],
       [   19.,   750.,   150.,     0.],
       [   20.,  1000.,   150.,     0.],
       [   21.,     0.,   200.,     0.],
       [   22.,   250.,   200.,     0.],
       [   23.,   500.,   200.,     0.],
       [   24.,   750.,   200.,     0.],
       [   25., 

In [31]:
elements

array([[  1.,   1.,   2.,   7.,   6.],
       [  2.,   2.,   3.,   8.,   7.],
       [  3.,   3.,   4.,   9.,   8.],
       [  4.,   4.,   5.,  10.,   9.],
       [  5.,   6.,   7.,  12.,  11.],
       [  6.,   7.,   8.,  13.,  12.],
       [  7.,   8.,   9.,  14.,  13.],
       [  8.,   9.,  10.,  15.,  14.],
       [  9.,  11.,  12.,  17.,  16.],
       [ 10.,  12.,  13.,  18.,  17.],
       [ 11.,  13.,  14.,  19.,  18.],
       [ 12.,  14.,  15.,  20.,  19.],
       [ 13.,  16.,  17.,  22.,  21.],
       [ 14.,  17.,  18.,  23.,  22.],
       [ 15.,  18.,  19.,  24.,  23.],
       [ 16.,  19.,  20.,  25.,  24.]])

In [32]:
constrained

array([ 1,  6, 11, 16, 21])

In [33]:
loaded

array([ 5, 10, 15, 20, 25])

## Write input file

In [43]:
filename = 'test.inp'

elementtype = 's4r'

In [65]:
outfile = open(filename, "wt")

outfile.write("** Lab 02 input file test\n")

outfile.write("**\n")
outfile.write("** NODES\n")
outfile.write("**\n")
outfile.write("*Node, nset = nglobal\n")
[outfile.write("{0:4d},{1:8},{2:8},{3:5}\n".format(int(nodes[i,0]),nodes[i,1], nodes[i,2], nodes[i,3])) \
 for i in range(nodes.shape[0])]

outfile.write("**\n")
outfile.write("** ELEMENTS\n")
outfile.write("**\n")
outfile.write("*Element, type = {0}\n".format(elementtype))
[outfile.write("{0:4d},{1:4d},{2:4d},{3:4d},{4:4d}\n".format(*([elements[i,j]) for j in range(elements.shape[1])]) \
 for i in range(elements.shape[0]) )]
outfile.close()


TypeError: must be str, not generator

In [61]:
"{0},{1}".format(*[int(elements[0,j]) for j in range(2)])

'1,1'

[1, 1, 2, 7, 6]